name: Deploy to cPanel

on:
  push:
    branches:
      - main-ng  # یہی وہ برانچ ہے جس پر آپ کام کریں گے

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4
        with:
          ref: main-ng  # یہاں بھی برانچ کا نام

      - name: Deploy Files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # cPanel پر جہاں فائلیں جانی ہیں
          local-dir: ./ # آپ کے گٹ ہب رپو میں فائلیں کہاں ہیں (جوڑ سے شروع)